var windData = [{
    "header": {
        "discipline": 0,
        "disciplineName": "Meteorological products",
        "gribEdition": 2,
        "gribLength": 133963,
        "center": 7,
        "centerName": "US National Weather Service - NCEP(WMC)",
        "subcenter": 0,
        "refTime": "2014-11-30T06:00:00.000Z",
        "significanceOfRT": 1,
        "significanceOfRTName": "Start of forecast",
        "productStatus": 0,
        "productStatusName": "Operational products",
        "productType": 1,
        "productTypeName": "Forecast products",
        "productDefinitionTemplate": 0,
        "productDefinitionTemplateName": "Analysis/forecast at horizontal level/layer at a point in time",
        "parameterCategory": 2,
        "parameterCategoryName": "Momentum",
        "parameterNumber": 2,
        "parameterNumberName": "U-component_of_wind",
        "parameterUnit": "m.s-1",
        "genProcessType": 2,
        "genProcessTypeName": "Forecast",
        "forecastTime": 6,
        "surface1Type": 100,
        "surface1TypeName": "Isobaric surface",
        "surface1Value": 85000,
        "surface2Type": 255,
        "surface2TypeName": "Missing",
        "surface2Value": 0,
        "gridDefinitionTemplate": 0,
        "gridDefinitionTemplateName": "Latitude_Longitude",
        "numberPoints": 65160,
        "shape": 6,
        "shapeName": "Earth spherical with radius of 6,371,229.0 m",
        "gridUnits": "degrees",
        "resolution": 48,
        "winds": "true",
        "scanMode": 0,
        "nx": 52,
        "ny": 59,
        "basicAngle": 0,
        "subDivisions": 0,
        "lo1": 113.207,
        "la1": 42.7022,
        "lo2": 359,
        "la2": -90,
        "dx": 0.12172211350293503,
        "dy": 0.09065576592082614
    },
    "data": [],
    "meta": {
        "date": "2014-11-30T12:00:00.000Z"
    }
}, {
    "header": {
        "discipline": 0,
        "disciplineName": "Meteorological products",
        "gribEdition": 2,
        "gribLength": 133963,
        "center": 7,
        "centerName": "US National Weather Service - NCEP(WMC)",
        "subcenter": 0,
        "refTime": "2014-11-30T06:00:00.000Z",
        "significanceOfRT": 1,
        "significanceOfRTName": "Start of forecast",
        "productStatus": 0,
        "productStatusName": "Operational products",
        "productType": 1,
        "productTypeName": "Forecast products",
        "productDefinitionTemplate": 0,
        "productDefinitionTemplateName": "Analysis/forecast at horizontal level/layer at a point in time",
        "parameterCategory": 2,
        "parameterCategoryName": "Momentum",
        "parameterNumber": 3,
        "parameterNumberName": "V-component_of_wind",
        "parameterUnit": "m.s-1",
        "genProcessType": 2,
        "genProcessTypeName": "Forecast",
        "forecastTime": 6,
        "surface1Type": 100,
        "surface1TypeName": "Isobaric surface",
        "surface1Value": 85000,
        "surface2Type": 255,
        "surface2TypeName": "Missing",
        "surface2Value": 0,
        "gridDefinitionTemplate": 0,
        "gridDefinitionTemplateName": "Latitude_Longitude",
        "numberPoints": 65160,
        "shape": 6,
        "shapeName": "Earth spherical with radius of 6,371,229.0 m",
        "gridUnits": "degrees",
        "resolution": 48,
        "winds": "true",
        "scanMode": 0,
        "nx": 52,  //步长
        "ny": 59,  //步长
        "basicAngle": 0,
        "subDivisions": 0,
        "lo1": 113.207,  //大小
        "la1": 42.7022,  //最大
        "lo2": 359,
        "la2": -90,
        "dx": 0.12172211350293503, //经纬度差 / 步长
        "dy": 0.09065576592082614  //经纬度差 / 步长
    },
    "data": [],
    "meta": {
        "date": "2014-11-30T12:00:00.000Z"
    }
}];